baseURL = "http://localhost"
# When generating for deployment, be sure to set:
# baseURL = "https://nazavode.github.io/meetupcpp-dec-2018/"

languageCode = "en-us"
disableKinds = ["taxonomy", "taxonomyTerm"]

theme = "reveal-hugo"

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true

[params.reveal_hugo]
reveal_cdn = "https://cdnjs.cloudflare.com/ajax/libs/reveal.js/3.7.0"
