baseURL = "http://localhost"
languageCode = "en-us"
disableKinds = ["taxonomy", "taxonomyTerm"]

theme = "reveal-hugo"

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true

