#!/bin/bash

set -eo pipefail

_curdir="$(cd "$( dirname "${BASH_SOURCE[0]}" )" > /dev/null && pwd)"
_flamegraph_home="${_curdir}/external/flamegraph"
_stackcollapse="${_flamegraph_home}/stackcollapse-perf.pl"
_flamegraph="${_flamegraph_home}/flamegraph.pl"

_folded_file="$(mktemp -p ${TMPDIR:-/tmp/} perf.folded.XXXX)"
_flamegraph_file="$(mktemp -p ${TMPDIR:-/tmp/} --suffix=.svg flamegraph.XXXX)"

set -x

# 1. Collapse all stack traces to a single line for each unique symbol
perf script | ${_stackcollapse} > ${_folded_file}

#2. Generate actual flamegraph from folded stack file
${_flamegraph} ${_folded_file} > ${_flamegraph_file}

# 3. Open!
xdg-open ${_flamegraph_file}
