#!/bin/bash

set -eo pipefail

if [ "$#" -ne 1 ]; then
    echo "usage: $(basename $0) <governor policy>"
    exit 1
fi

_cpuids="$(grep processor /proc/cpuinfo | cut -f2 -d:)"

for i in ${_cpuids}; do
    sudo cpufreq-set -c $i -g ${1}
done
